algoritmo "Triangulo"
// Função :
// Autor : Luis Eduardo Ramos Tezin
// Data : 09/04/2019
// Seção de Declarações 
// Questão 5
// Faça um programa que calcula e mostra a área de um triângulo. Sabe-se que Área = (base * altura) / 2.
var
   area, base, altura: Real
inicio
      escreva("Base do triângulo: ")
      leia(base)
      escreva("Altura do triângulo: ")
      leia(altura)
      area <- (base * altura) / 2
      escreva("Área total: ", area)
fimalgoritmo
