algoritmo "Multiplos7"
// Função :
// Autor : Luis Eduardo Ramos Tezin
// Data : 11/04/2019
// Questão 4
// Faça um algoritmo que imprima os múltiplos positivos de 7, inferiores a 1000.
// Seção de Declarações 
var
   count: Inteiro
inicio
      para count de 1 ate 1000 faca
           se (count mod 7 = 0) entao
              escreval(count, " é multiplo de 7.")
           fimse
      fimpara
fimalgoritmo
